### 全件取得
GET http://localhost:3000/todo

### 1件追加
POST http://localhost:3000/todo
Content-Type: application/json

{
  "title": "test",
  "status": "waiting"
}

### 1件更新
PUT http://localhost:3000/todo
Content-Type: application/json

{
  "id": ":id",
  "title": "test update",
  "status": "done"
}

### 1件削除
DELETE http://localhost:3000/todo/:id